spring:
  application:
    name: slcnapp
  datasource:
    url: "${SLCN_MYSQL_URL}"
    username: "${SLCN_MYSQL_USER}"
    password: "${SLCN_MYSQL_PW}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: "${SLCN_REDIS_URL}"
      port: "${SLCN_REDIS_PORT}"
      password: "${SLCN_REDIS_PW}"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        use_sql_comments: false
        format_sql: false
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  jwt:
    secretKey: "${SLCN_JWT_SECRETKEY}"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate: info

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /api-test
    enabled: false

upload:
  path: "${SLCN_UPLOAD_PATH}"

cookie:
  expire:
    time: 1209600
login:
  fail:
    limit:
      count: 5
  limit:
    clear:
      time: 300

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    enabled: true
