spring:
  application:
    name: slcnapp
  datasource:
    url: "${SLCN_POSTGRESQL_URL}"
    username: "${SLCN_POSTGRESQL_USER}"
    password: "${SLCN_POSTGRESQL_PW}"
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: "${SLCN_MONGODB_URL}"
    redis:
      host: "${SLCN_REDIS_URL}"
      port: "${SLCN_REDIS_PORT}"
      password: "${SLCN_REDIS_PW}"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        use_sql_comments: false
        format_sql: false
    generate-ddl: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secretKey: "${SLCN_JWT_SECRETKEY}"
    algorithm: "${SLCN_JWT_ALGORITHM:HS512}"
    accessAudiences: "${SLCN_JWT_ACCESS_AUDIENCES:slcn-platform}"
    refreshAudience: "${SLCN_JWT_REFRESH_AUDIENCE:slcn-auth-refresh}"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org:
      hibernate: info

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    enabled: false

slcn:
  domain: "${SLCN_DOMAIN_LIST}"
  upload:
    path: "${SLCN_UPLOAD_PATH}"

cookie:
  expire:
    time: 1209600
  secure: false
  sameSite: Lax
login:
  fail:
    limit:
      count: 5
  limit:
    clear:
      time: 300

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    path: /api-test
    enabled: true
