plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':slcn-rest')
    implementation project(':slcn-auth')

    testImplementation project(':slcn-aggregate')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocVersion}"

    // 시큐리티 체인 테스트에서 JwtTokenProvider를 스텁하려면 Claims 시그니처가 필요하다.
    testImplementation "io.jsonwebtoken:jjwt-api:${rootProject.ext.jjwtVersion}"
}
