dependencies {
    implementation project(':slcn-spec')
    implementation project(':slcn-aggregate')
    implementation project(':slcn-auth')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.mnode.ical4j:ical4j:4.3.0'
}
